[package]
name = "finquant"
version = "0.0.6"
authors = ["Jeremy Wang <j.wang@quantransform.co.uk>"]
edition = "2021"
license = "MIT"
description = "Experimental Rust Quant Library"
keywords = ["quant"]
readme = "../README.md"

[features]

[dependencies]
chrono = "^0.4.31"
